# for Watermill development purposes.
# For Watermill based application docker please check https://watermill.io/docs/getting-started/

version: '3'
services:
  firestore:
    image: mtlynch/firestore-emulator:latest
    env_file:
      - "./.env"
    ports:
      - "8080:8787"
    restart: unless-stopped
