# for Watermill development purposes.
# For Watermill based application docker please check https://watermill.io/docs/getting-started/

version: '3'
services:
  firestore:
    build:
      context: ./emulator
    env_file:
      - "./.env"
    ports:
      - 8080:8080
    restart: unless-stopped
