name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FIRESTORE_EMULATOR_HOST: localhost:8081
  FIRESTORE_PROJECT_ID: test

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run Firestore emulator
        uses: mickfeech/firestore-emulator-action@0.0.12
        with:
          fireStoreProjectID: test

      - name: Run tests
        run: make ci
